# Generated by Django 5.1.4 on 2024-12-09 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nike_name",
                    models.CharField(
                        blank=True, default="", max_length=23, verbose_name="昵称"
                    ),
                ),
                (
                    "birthday",
                    models.DateTimeField(blank=True, null=True, verbose_name="生日"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女")],
                        default="male",
                        max_length=6,
                        verbose_name="性别",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="地址"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="image/default.jpg",
                        max_length=255,
                        upload_to="image/%Y/%m",
                        verbose_name="用户头像",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
        ),
    ]
