# Generated by Django 5.1.4 on 2024-12-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_userprofile_address_userprofile_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="nike_name",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=23, null=True, verbose_name="昵称"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="password",
            field=models.CharField(
                default=1234567890, max_length=32, verbose_name="密码"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="username",
            field=models.CharField(
                db_index=True, default="zhangsan", max_length=32, verbose_name="用户名"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=32, verbose_name="邮箱"),
        ),
    ]
