# Generated by Django 5.1.4 on 2024-12-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_emailverification_alter_userprofile_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
    ]
