# Generated by Django 5.1.4 on 2024-12-12 05:46

import utils.user_avatar_upload_to
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_userprofile_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                default="image/default.jpg",
                max_length=255,
                upload_to=utils.user_avatar_upload_to.user_avatar_upload_to,
                verbose_name="用户头像",
            ),
        ),
    ]
