# Generated by Django 5.1.4 on 2025-01-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_userprofile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="signature",
            field=models.TextField(
                blank=True, default="", max_length=50, verbose_name="个性签名"
            ),
        ),
    ]
