# Generated by Django 5.1.4 on 2025-01-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_userprofile_signature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="signature",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="个性签名"
            ),
        ),
    ]
