# Generated by Django 5.1.4 on 2025-01-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_category_tag_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
