# Generated by Django 5.1.4 on 2025-01-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_sidebar"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_hot",
            field=models.BooleanField(default=False, verbose_name="是否热门"),
        ),
        migrations.AddField(
            model_name="post",
            name="pv",
            field=models.IntegerField(default=0, verbose_name="浏览量"),
        ),
    ]
