# Generated by Django 5.1.4 on 2025-01-19 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_post_favorited_users_post_liked_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="post_images/", verbose_name="图片"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="blog.post",
                        verbose_name="所属文章",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章图片",
                "verbose_name_plural": "文章图片",
            },
        ),
    ]
