# Generated by Django 5.1.4 on 2025-01-19 20:59

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_postimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="image",
            field=models.ImageField(
                upload_to=blog.models.post_image_upload_to, verbose_name="图片"
            ),
        ),
    ]
