# Generated by Django 5.1.4 on 2025-02-27 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_remove_post_tags_post_tags"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PostImage",
        ),
    ]
